apiVersion: v1
kind: Service
metadata:
  labels:
    app: kupping-backend
  name: kupping-backend-service
  namespace: default
spec:
  ports:
  - port: 80
    name: http-backend
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https-backend
    protocol: TCP
    targetPort: 443
  selector:
    app: kupping-backend
  sessionAffinity: None
  type: ClusterIP