apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "kupping-backend"
  namespace: "default"
  labels:
    app: "kupping-backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kupping-backend"
  template:
    metadata:
      labels:
        app: "kupping-backend"
    spec:
      volumes:
      - name: tickets
        persistentVolumeClaim:
          claimName: ticket-disk
      containers:
      - name: backend
        image: gcr.io/kupping/github.com/maiconpintoabreu/kupping/backend
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/var/tickets"
          name: tickets
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: kupping-backend-config
        - name: docker
          valueFrom:
            configMapKeyRef:
              key: docker
              name: kupping-backend-config
        - name: MONGO
          valueFrom:
            configMapKeyRef:
              key: MONGO
              name: kupping-backend-config
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: kupping-backend-config
        - name: MONGO_PREFIX
          valueFrom:
            configMapKeyRef:
              key: MONGO_PREFIX
              name: kupping-backend-config
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              key: MONGO_USER
              name: kupping-backend-config
        - name: MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGO_PASSWORD
              name: kupping-backend-config
        - name: MONGO_PARAMS
          valueFrom:
            configMapKeyRef:
              key: MONGO_PARAMS
              name: kupping-backend-config
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MONGO_DATABASE
              name: kupping-backend-config
