name: Build and Deploy with Skaffold

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_KEY: ${{ secrets.GKE_KEY }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  $GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
  SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
  CONFIG_MAP: ${{ secrets.CONFIG_MAP }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin
        mkdir certs
        echo $SSL_FULLCHAIN > certs/fullchain.pem && echo $SSL_PRIVKEY > certs/privkey.pem
        mkdir ~/.kube
        echo $KUBE_CONF > ~/.kube/config
      
    # Build the Docker image
    - name: Build
      run: |        
        skaffold build

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        skaffold deploy
